name: lint-formatter

on:
  workflow_call:
    inputs:
      file_patterns:
        required: true
        type: string
      command:
        required: true
        type: string
      commit_message:
        required: true
        type: string

jobs:
  lint-formatter-job:
    name: Auto-apply file formatting

    runs-on: ubuntu-latest
    steps:
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@main

      - id: get-diff
        uses: ultimaker/cura-workflows/.github/actions/get-diff@main
        with:
          files: ${{ inputs.file_patterns }}

      - name: Format files
        if: steps.get-diff.outputs.files != ''
        run: ${{ inputs.command }} ${{ steps.get-diff.outputs.files_quoted }}

      - uses: stefanzweifel/git-auto-commit-action@v7
        if: steps.get-diff.outputs.files != ''
        with:
          commit_message: ${{ inputs.commit_message }}
          file_pattern: ${{ steps.get-diff.outputs.files }}

